#' @title Regional Paired T-Test and Fold-Change for Significant Trend Regions
#' @description
#' For each significant trend region identified by
#' \code{\link{analyzeLipidRegion}} (Increase / Decrease), performs an
#' independent region-level paired t-test on feature-wise group-mean abundances
#' (feature = pairing unit), and summarizes the region's fold-change. This
#' provides an explainable, permutation-free statistic to accompany the
#' smoothed permutation test result, and is also used internally by
#' \code{\link{plotRegion1D}}/ \code{\link{plotRegion2D}} to validate large
#' regions before coloring them (see their \code{regional_p_cutoff} argument
#' for the significance level applied to \code{regional.test.pval} in that
#' decision).
#' @param object A LipidTrendSE object generated by \code{analyzeLipidRegion()}.
#' @param p_cutoff Numeric. Significance threshold used to define which
#' features belong to a region, based on the smoothed permutation test
#' (\code{smoothing.pval.BH < p_cutoff}). Should match the \code{p_cutoff}
#' used when visualizing the same result with \code{\link{plotRegion1D}}/
#' \code{\link{plotRegion2D}}. Default is \code{0.05}.
#' @return
#' A data frame with one row per direction (\code{Increase}/\code{Decrease}):
#' \describe{
#'   \item{direction}{\code{"Increase"} or \code{"Decrease"}.}
#'   \item{n.features}{Number of significant features in that direction.}
#'   \item{regional.test.pval}{Paired t-test p-value on feature-wise
#'   group-mean abundance across the significant features. \code{NA} when
#'   \code{n.features <= 5} (a paired t-test on 5 or fewer pairs is too
#'   underpowered to be trustworthy).}
#'   \item{regional.FC}{Regional fold-change on the linear scale. This is the
#'   \strong{median} fold-change across the significant features in that
#'   direction -- a median rather than a mean, so that a single extreme
#'   feature cannot dominate the summary of the region.}
#'   \item{log2.regional.FC}{The same quantity on the log2 scale: the median
#'   log2 fold-change across those features. Equal to
#'   \code{log2(regional.FC)}.}
#' }
#' If \code{split_chain=TRUE} in the analysis, a list with
#' \code{even_result}/\code{odd_result} data frames as above.
#' @examples
#' data("lipid_se_CL")
#' res_se <- analyzeLipidRegion(
#'     lipid_se=lipid_se_CL, ref_group="sgCtrl", split_chain=FALSE,
#'     chain_col=NULL, radius=3, permute_time=100)
#' tab <- regionalTestFC(res_se)
#' @export
#' @seealso
#' \code{\link{analyzeLipidRegion}} for generating the input LipidTrendSE object
#' \code{\link{plotRegion1D}} and \code{\link{plotRegion2D}} for visualization
setGeneric(
    "regionalTestFC",
    function(object, p_cutoff=0.05) standardGeneric("regionalTestFC"))

#' @rdname regionalTestFC
#' @aliases regionalTestFC,LipidTrendSE-method
#' @exportMethod regionalTestFC
setMethod("regionalTestFC", "LipidTrendSE", function(object, p_cutoff=0.05) {
    if (!is.numeric(p_cutoff) || p_cutoff < 0 || p_cutoff > 1) {
        stop("p_cutoff must be a numeric value between 0 and 1")
    }
    if (.split_chain(object)) {
        even_results <- even_chain_result(object)
        odd_results <- odd_chain_result(object)
        return(list(
            even_result=.pairedFCTest(even_results, object, p_cutoff),
            odd_result=.pairedFCTest(odd_results, object, p_cutoff)))
    } else {
        results <- result(object)
        return(.pairedFCTest(results, object, p_cutoff))
    }
})

# Region-level paired t-test and fold-change summary. Shared internal
# helper used by both regionalTestFC() and the region-validation logic in
# plotRegion1D()/plotRegion2D(), so the reported table and the plot
# coloring never disagree. chain_result is a data frame from result(),
# even_chain_result(), or odd_chain_result(); object is the LipidTrendSE
# (or the SummarizedExperiment it wraps), used to read
# colData(object)$group and assay(object). Returns a data frame with
# columns direction, n.features, regional.test.pval, regional.FC,
# log2.regional.FC. regional.FC is the median fold-change across the
# region's significant features; the local variables below keep the
# name median.FC to make that identity explicit at the assignment.
.pairedFCTest <- function(chain_result, object, p_cutoff) {
    empty_row <- function(direction_label) {
        data.frame(
            direction=direction_label, n.features=0L,
            regional.test.pval=NA_real_, regional.FC=NA_real_,
            log2.regional.FC=NA_real_)
    }
    if (is.null(chain_result) || nrow(chain_result) == 0) {
        return(rbind(empty_row("Increase"), empty_row("Decrease")))
    }
    groups <- unique(SummarizedExperiment::colData(object)$group)
    if (length(groups) != 2) {
        stop(
            "regionalTestFC() requires exactly 2 groups; found ",
            length(groups))
    }
    grouped_avg_abund <- vapply(groups, function(g) {
        idx <- SummarizedExperiment::colData(object)$group == g
        rowMeans(SummarizedExperiment::assay(object)[, idx, drop=FALSE])
    }, FUN.VALUE=numeric(nrow(object)))
    rownames(grouped_avg_abund) <- rownames(object)

    run_one <- function(direction_label, sign_label) {
        sig <- chain_result$direction == sign_label &
            chain_result$smoothing.pval.BH < p_cutoff
        feat_tab <- chain_result[sig, , drop=FALSE]
        n <- nrow(feat_tab)
        if (n == 0) return(empty_row(direction_label))
        median.log2FC <- stats::median(feat_tab$log2.FC)
        median.FC <- 2 ^ median.log2FC
        if (n <= 5) {
            return(data.frame(
                direction=direction_label, n.features=n,
                regional.test.pval=NA_real_,
                regional.FC=round(median.FC, 2),
                log2.regional.FC=round(median.log2FC, 2)))
        }
        sub <- grouped_avg_abund[rownames(feat_tab), , drop=FALSE]
        log_sub <- log(sub, base=2)
        test <- tryCatch(
            stats::t.test(log_sub[, 1], log_sub[, 2], paired=TRUE),
            error=function(e) NULL)
        data.frame(
            direction=direction_label, n.features=n,
            regional.test.pval=if (is.null(test)) NA_real_ else test$p.value,
            regional.FC=round(median.FC, 2),
            log2.regional.FC=round(median.log2FC, 2))
    }
    rbind(run_one("Increase", "+"), run_one("Decrease", "-"))
}

# Whether a plot should switch to paired-test-based region coloring. A
# figure only switches from the smoothed-permutation coloring to
# paired-test-based coloring when *every* direction in that figure has a
# usable regional.test.pval (fc_table is the output of .pairedFCTest() for
# one chain result; .pairedFCTest() already sets regional.test.pval to NA
# whenever n.features <= 5, so "usable" and "n.features > 5" are the same
# condition -- checked here via the NA rather than re-deriving the
# threshold a second time). If any direction lacks a usable p-value, the
# whole figure keeps the original coloring unchanged, so a single figure
# never mixes two different statistical criteria. regional_p_cutoff is the
# significance level applied to regional.test.pval -- independent from
# p_cutoff, which only governs region membership via smoothing.pval.BH.
# Returns a named logical vector c(Increase=, Decrease=): whether each
# direction is validated (both TRUE when the whole-figure gate is FALSE,
# i.e. the original coloring applies unchanged).
.regionColorDecision <- function(fc_table, regional_p_cutoff) {
    use_paired_test <- all(!is.na(fc_table$regional.test.pval))
    if (!use_paired_test) {
        return(c(Increase=TRUE, Decrease=TRUE))
    }
    validated <- vapply(c("Increase", "Decrease"), function(d) {
        pval <- fc_table$regional.test.pval[fc_table$direction == d]
        isTRUE(pval < regional_p_cutoff)
    }, FUN.VALUE=logical(1))
    validated
}
